main: dev.riftmc.PlayerEssentials.Essentials
name: Essentials
author: Quizaciously
version: 0.2-alpha.3
api-version: 1.16
description: A light-weight build of Essentials.
softdepend: [ Vault, PlaceholderAPI ]