main: me.riley.HeroicEssentials
name: HeroicEssentials
author: Riley
version: 1.5
description: A light-weight essentials plugin
depend: [Vault]
commands:
  heroicessentials:
    description: Plugin information.
  time:
    description: Control the time.
  discord:
    description: Get the discord link.
  store:
    description: Get the store link.
  tpa:
    description: Request to teleport to a player
  tpaccept:
    description: Accept a request from players
  tpdeny:
    description: Deny a request from a player
  teleport:
    description: Teleport to a player
    aliases: [tp]
  tphere:
    description: Teleport a player to you
  gmc:
    description: Set your gamemode to creative
  gms:
    description: Set your gamemode to survival
  gamemode:
    description: Set your gamemode
    aliases: [gm]
  tell:
    description: Message other players
    aliases: [msg, message, whisper, w]
  reply:
    description: Reply to the last user you messaged
    aliases: [r]
  home:
    description: Go to your home
  sethome:
    description: Set your home
  delhome:
    description: Delete your home
  homes:
    description: Get a list of your homes
  nick:
    description: Nickname yourself
<<<<<<< Updated upstream
  warp:
    description: Warp to another location
  setwarp:
    description: Set a warp
  delwarp:
    description: Delete a warp
  balance:
    description: Get your balance
    aliases: [bal]
=======
    aliases: [nickname]
  warp:
    description: Warp to another location
  setwarp:
    description: Create a warp
  delwarp:
    description: Deleate a warp
>>>>>>> Stashed changes
  pay:
    description: Pay people money
    aliases: [transfer]
  banknotes:
<<<<<<< Updated upstream
    description: Get bank notes
    aliases: [checks]
=======
    description: Write a check
    aliases: [checks, banknote]
  balance:
    description: Check your balance
    aliases: [bal]
>>>>>>> Stashed changes
